### ISSUE TITLE
SSDV Handler Re-Host

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/habitat-server-transition#8]
... i think @fsphil is onto this one.

**Comment by fsphil** [comment]
I'm planning to set up a simple Linode VM for this.

**Comment by KevWal** [comment]
Thanks Phil, if you want any help or a contribution please shout.

**Comment by fsphil** [comment]
This is up and running now at https://ssdv.sanslogic.co.uk/
I'll do some more testing and tweaking on this new server before asking for ssdv.habhub.org to be pointed at it.

**Comment by fsphil** [comment]
The migration is now complete. I took the opportunity to update a few things I've been meaning to do for a while now:

* The packet submission requests no longer render the image or do any database work. This is now handled by a background service.
* The live data requests always read from cache, updated by the background service.
* Tidied up the database structure to reduce the size a little.
* Archived images and packet data are stored on a separate server.
